import './globals.css';
import type { Metadata } from 'next';
import { Noto_Sans_KR } from 'next/font/google';
import { ReactNode } from 'react';
import { Footer, Header, Sidebar } from '@/components';

const noto = Noto_Sans_KR({ subsets: ['latin'], weight: ['300', '400', '500', '700'] });

export const metadata: Metadata = {
  title: 'Create My Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={noto.className}>
        <Header/>
        <div>
          <Sidebar/>
          <div>
            {children}
          </div>
        </div>
        <Footer/>
      </body>
    </html>
  );
}
